spring:
  datasource:
    url: jdbc:h2:mem:mydb
    #url: jdbc:h2:file:/data/demo
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
        ddl-auto: create-drop
  h2:
    console.enabled: true

# App Properties
app-interview:
  app:
    jwtCookieName: app-interview
    jwtSecret: secretKeySecretKey
    jwtExpirationMs: 86400000